### ISSUE TITLE
Bonus dice in Bonus/Penalty area

### ISSUE THREAD

**Issue by kingofthebling** [Actoba/roll20-character-sheets#89]
I'd like to point out 2 issues I've noticed related to the bonus/penalty area.

First, bonuses added to ability checks are not factored in to initiative rolls. Since initiative rolls are dexterity checks, any bonuses or penalties should be included.

Second, when adding a die modifier to an attack roll in the bonus/penalty area the displayed result will indicate a critical hit if the bonus die is a maximum and the original d20 is not. For example, if you are under the effects of the Bless spell, you would naturally want to include a bonus 1d4 on all melee and ranged attack rolls. If you put a 1d4 in those sections of the Bonus/Penalty area and make an attack, the Chat area of roll20 will register a critical hit if a 4 is rolled on the d4, regardless of what was rolled on the d20.  In order to verify whether or not the roll was actually a critical hit you have to scroll over the result and parse several lines of text to find the original d20 roll.  This is very time consuming.

**Comment by Actoba** [comment]
I assume that this is referencing one of the DnD 5e sheets?

If this is for the original 5e sheet and not the shaped one then I can say the following - 
* There is a seperateentry box for initiative bonuses (next to the initiative section).  The intended use here is that bonus which impact initiative should go here and not in the skill/ability bonus field.  If you have a +2 bonus to all ability checks you should add a 2 to both the skill/ability bonus section and the initiative bonus field.  The reason its done like this is because there are many situations/feats/class abilities that provide a bonus for initiative rolls only and it made sense to make sure that the total bonus applied to initive was applied in a single place instead of accross 2 (the purely initiative bonus and the skill/ability bonus)
* The crit highlighting is a function of the Roll20 dice rolling system and theres nothing sheet authors can do to mitigate this.  Users of the sheet can however enter the bonuses using a syntax that means a dice roll would never highlight as a crit.  So for example, lets suppose you wanted to add 1d4 to all melee attack rolls.  If you just add "1d4" in the appropriate field in the bonus section then as you mention the entire roll is highlighted as a crit (or fail) if any dice in the roll hits it's highest (or lowest) number.  If you instead enter this "1d4cs>5cf<0" then the 1d4 you roll can never crit (or crit fail) because the extra characters on the end indicate that it should only indicate crit success for this roll on a result of 5 or more, and a crit fail on a result of 0 or less.  Obviously you can adjust this for the specific dice roll you are doing to ensure that the values for critting are outside what is possible for a single one of those dice to roll.  Some other examples - "1d6cs>7cf<0", "6d6cs>7cf<0", "1d100cs>101cf<0"

Hope this helps
