### ISSUE TITLE
Problems with spells on mobile

### ISSUE THREAD

**Issue by Sgmaniac1255** [Actoba/roll20-character-sheets#92]
I'm having an issue with the spell section of the sheet on my IPad. on the website it's fully filled out with the spells, descriptions and details. however when i load the character on the IPad app, the sheet shows the spell slots, however all the fields are blank and if i cast the Macro from the IPad it gives a blank spell cast.

character sheet on PC in Chrome
![image](https://cloud.githubusercontent.com/assets/5742529/12079018/2af1a27c-b1ef-11e5-9e60-d831d1e2ecb5.png)

Cast on PC in Chrome
![image](https://cloud.githubusercontent.com/assets/5742529/12079036/9d7dda68-b1ef-11e5-825e-7c455edb806b.png)

same sheet on IPad
![20160103_075509](https://cloud.githubusercontent.com/assets/5742529/12079031/7b7c4080-b1ef-11e5-9b1b-7ec1e3439149.jpg)

Cast from IPad
![image](https://cloud.githubusercontent.com/assets/5742529/12079040/b6328504-b1ef-11e5-92ee-8d23b085e647.png)

**Comment by Sgmaniac1255** [comment]
Sorry, i should have specified that this was for the DnD_5e Sheet. i didn't realize that all your sheets were listed under the same project. my appologies

**Comment by Actoba** [comment]
Hi,

It's very unlikely that this is an issue with the sheet itself and much more likely to be an iassue with the character/campaign.  The blank spell output is simply because there is no data loaded into the sheet so it has nothing to display.

My first suggestion would be to confirm whether this happens for all characters within the campaign (or just yours).  If you are not the GM of the campaign you'll have to ask the GM to assign you another character sheet to test with.

Similarly, is this happening for you in every campaign or just this one?  You can create a new campaign and create a character in it to test.

I'll give the sheet a quick once over but you may be better contacting roll20 support or posting on the roll20 forums for assistance as it is very unlikely that this is being caused by the sheet itself.

Thanks
Actoba
